# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Kraken
tagline:          A Clean Systems Language
url:              https://github.com/Limvot/kraken/
paginate:         1
baseurl:          http://limvot.github.io/kraken/
author:
  name:           Nathan Braswell
  url:            http://limvot.github.io/
  email:          miloignis@gmail.com 

# Custom vars
version:          0.0.0
github:
repo:           https://github.com/Limvot/kraken/
